name: Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: branch to deploy
        default: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout coming soon repo
        uses: actions/checkout@v3
        with:
          repository: Southern-Frogs/coming-soon
          token: ${{secrets.PULL_FROM_COMING_SOON}}
        env: 
          PULL_FROM_COMING_SOON: ${{secrets.PULL_FROM_COMING_SOON}}

      - name: npm install
        run: npm install
        
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLIC_URL: "/bonpelloweb"
